### ISSUE TITLE
블로그 메인 디자인

### ISSUE THREAD

**Issue by tlatlawogns** [wjsdmlwls/Loseweight_2019_2b03#2]
블로그 메인이미지에 프로젝트명 학년  빨간 박스위치에 포토샵으로 수정하기
![캡처](https://user-images.githubusercontent.com/54388278/63912964-80a22e80-ca69-11e9-8ba5-3aaccb986bb2.PNG)

**Comment by SunrYongLee** [comment]
말씀하신게 뭔데요

**Comment by wjsdmlwls** [comment]
수정완료
